export const seedProducts = [
    { name: 'Shadowflare Dragon (Holographic)', category: 'cards', availability: 'available', price: 299.99, stock: 5, description: 'Rare holographic shadow-type dragon from the First Awakening set.' },
    { name: 'Midnight Specter #1 (First Edition)', category: 'comics', availability: 'vaulted', price: 1250.00, stock: 1, description: 'The debut of the Specter. Mint condition (CGC 9.8).' },
    { name: 'Iron Sentinel: Mark IV Statue', category: 'figures', availability: 'pre-order', price: 450.00, stock: 10, description: 'Hand-painted 1/4 scale resin statue with LED functions.' },
    { name: 'Prism Knight #42 (Signed)', category: 'comics', availability: 'sold-out', price: 85.00, stock: 0, description: 'Signed by the original artist. Limited run cover.' },
    { name: 'Neon Samurai (Ghost Variant)', category: 'figures', availability: 'low-stock', price: 120.00, stock: 3, description: 'Translucent armor variant. Only 500 units produced.' },
    { name: 'Void-Step Boots (Prop Replica)', category: 'memorabilia', availability: 'available', price: 599.00, stock: 2, description: 'Full-scale wearable replica from the Void Walker film.' },
    { name: 'Galactic Empress (Metal Card)', category: 'cards', availability: 'pre-order', price: 150.00, stock: 25, description: 'Laser-etched titanium card. Limited preorder edition.' },
    { name: 'Cyber-Punk 2099 Bust', category: 'figures', availability: 'low-stock', price: 320.00, stock: 4, description: 'Intricate cyberpunk-themed bust with neon accents.' },
    { name: 'Crimson Warlock #12', category: 'comics', availability: 'available', price: 12.99, stock: 50, description: 'Latest issue in the Crimson Warlock saga.' },
    { name: 'Ancient Relic (Sealed Booster)', category: 'cards', availability: 'vaulted', price: 2500.00, stock: 1, description: 'Sealed booster pack from the 1998 Alpha release.' },
    { name: 'Thunder-Clap Hammer (1:1 Scale)', category: 'memorabilia', availability: 'sold-out', price: 899.00, stock: 0, description: 'Heavyweight zinc alloy replica with leather handle.' },
    { name: 'Star-Child Figurine', category: 'figures', availability: 'available', price: 45.00, stock: 100, description: 'Adorable vinyl figure from the Star-Child series.' },
    { name: 'The Eternal Rogue #1 (Variant)', category: 'comics', availability: 'available', price: 25.00, stock: 15, description: 'Exclusive store variant cover by Jim Lee.' },
    { name: 'Mana-Leak (Error Print Card)', category: 'cards', availability: 'vaulted', price: 450.00, stock: 1, description: 'Famous misprint with inverted mana symbols.' },
    { name: 'Mech-Wolf (Transformation Set)', category: 'figures', availability: 'low-stock', price: 89.99, stock: 5, description: 'Fully articulated robot that transforms into a wolf.' },
    { name: 'Golden Phoenix Pin (Limited)', category: 'memorabilia', availability: 'sold-out', price: 35.00, stock: 0, description: 'Enamel pin with real 24k gold plating.' },
    { name: 'Super-Sonic Speedster #3', category: 'comics', availability: 'available', price: 9.99, stock: 40, description: 'High-octane superhero action. First appearance of Aero.' },
    { name: 'Deep-Sea Diver (Retro Series)', category: 'figures', availability: 'available', price: 29.99, stock: 60, description: 'Vintage-style 3.75 inch action figure.' },
    { name: 'Lunar Eclipse Foil Card', category: 'cards', availability: 'pre-order', price: 49.99, stock: 200, description: 'Special foil treatment for the Eclipse expansion.' },
    { name: 'Obsidian Blade (Letter Opener)', category: 'memorabilia', availability: 'available', price: 75.00, stock: 12, description: 'Hand-carved volcanic glass desk accessory.' },
    { name: 'Future-Cop: Patrol Cruiser', category: 'figures', availability: 'low-stock', price: 149.00, stock: 2, description: 'Die-cast police vehicle with working lights.' },
    { name: 'Solar Flare: Rise of Helios', category: 'comics', availability: 'available', price: 14.50, stock: 30, description: 'Graphic novel detailing the origin of Helios.' },
    { name: 'Frost-Giant 18" Statue', category: 'figures', availability: 'sold-out', price: 650.00, stock: 0, description: 'Massive resin statue with faux-snow base.' },
    { name: 'Mystic Eye (Gold Frame)', category: 'cards', availability: 'available', price: 120.00, stock: 8, description: 'Ultra-rare gold-bordered spell card.' },
    { name: 'The Last Guardian (Hardcover)', category: 'memorabilia', availability: 'available', price: 55.00, stock: 20, description: 'Premium art book with behind-the-scenes sketches.' },
    { name: 'Bio-Hazard Mutant #7', category: 'figures', availability: 'low-stock', price: 35.00, stock: 5, description: 'Glow-in-the-dark mutant action figure.' },
    { name: 'Shadow-Step Assassin #1', category: 'comics', availability: 'available', price: 5.99, stock: 100, description: 'New stealth-based superhero series.' },
    { name: 'Dragon-Scale Shield Replica', category: 'memorabilia', availability: 'vaulted', price: 1100.00, stock: 1, description: 'Authentic leather and steel shield from Dragon Age.' },
    { name: 'Warp-Drive (Signed Prototype)', category: 'cards', availability: 'sold-out', price: 3000.00, stock: 0, description: 'One of only 5 signed prototype cards in existence.' },
    { name: 'Jungle Predator (Camouflage)', category: 'figures', availability: 'available', price: 42.00, stock: 18, description: 'Highly detailed hunter with forest camo.' },
    { name: 'Speed-Force #101', category: 'comics', availability: 'pre-order', price: 7.99, stock: 500, description: 'Anniversary issue with holographic cover.' },
    { name: 'Royal Scepter (Jeweled Edition)', category: 'memorabilia', availability: 'sold-out', price: 450.00, stock: 0, description: 'Prop replica with synthetic rubies and sapphires.' },
    { name: 'Titan-Slayer Axe (Display)', category: 'memorabilia', availability: 'low-stock', price: 280.00, stock: 3, description: 'Stainless steel display axe with wall mount.' },
    { name: 'Phoenix-Down Phoenix Card', category: 'cards', availability: 'available', price: 15.00, stock: 150, description: 'Standard utility card for competitive play.' },
    { name: 'Urban Legend: The Ghoul', category: 'figures', availability: 'available', price: 24.00, stock: 45, description: 'Horror-themed collectible with poseable limbs.' },
    { name: 'Cosmic Voyager (Chrome Edition)', category: 'figures', availability: 'vaulted', price: 199.00, stock: 1, description: 'Limited chrome finish astronaut figure.' },
    { name: 'Hellfire Chronicles #6', category: 'comics', availability: 'available', price: 4.99, stock: 80, description: 'The battle for the underworld continues.' },
    { name: 'Kraken-Tooth Necklace', category: 'memorabilia', availability: 'low-stock', price: 95.00, stock: 4, description: 'Ethically sourced bone replica from the Kraken film.' },
    { name: 'Spirit-Walker Foil', category: 'cards', availability: 'available', price: 38.00, stock: 10, description: 'Rare foil card with spirit-shifting ability.' },
    { name: 'Stealth-Jet (Die-Cast)', category: 'figures', availability: 'pre-order', price: 55.00, stock: 60, description: 'Detailed 1:72 scale die-cast fighter jet.' },
    { name: 'Blade of the Immortal (Wooden)', category: 'memorabilia', availability: 'available', price: 120.00, stock: 6, description: 'Hand-crafted bokken used for film training.' },
    { name: 'Gravity-Girl #1', category: 'comics', availability: 'available', price: 6.50, stock: 200, description: 'Debut of the new gravity-defying heroine.' },
    { name: 'Stone-Gargoyle Bookends', category: 'memorabilia', availability: 'sold-out', price: 85.00, stock: 0, description: 'Heavy stone-cast bookends for your library.' },
    { name: 'Time-Traveler\'s Watch', category: 'memorabilia', availability: 'vaulted', price: 750.00, stock: 1, description: 'Authentic prop watch used in the Chronos film.' },
    { name: 'Acid-Rain Survivor Figure', category: 'figures', availability: 'available', price: 34.00, stock: 22, description: 'Post-apocalyptic warrior with gas mask.' },
    { name: 'Mirror-Force (Blue Foil)', category: 'cards', availability: 'low-stock', price: 110.00, stock: 2, description: 'Iconic trap card with rare blue lettering.' },
    { name: 'Ghost-Hunter: The Van', category: 'figures', availability: 'available', price: 65.00, stock: 14, description: 'Scale model of the iconic supernatural investigation van.' },
    { name: 'Samurai Jack-In-The-Box', category: 'figures', availability: 'available', price: 40.00, stock: 30, description: 'Quirky pop-culture toy with a katana surprise.' },
    { name: 'The Dark Knight: Cape Clip', category: 'memorabilia', availability: 'available', price: 25.00, stock: 50, description: 'Replica utility clip from the superhero suit.' },
    { name: 'Mythic Quest #500 (Finale)', category: 'comics', availability: 'sold-out', price: 19.99, stock: 0, description: 'Oversized final issue of the decade-long quest.' }
];